apiVersion: v1
kind: Service
metadata:
  name: localstack-service
  namespace: localstack
spec:
  selector:
    name: localstack
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 4566
      targetPort: 4566
      name: http
      nodePort: null
