apiVersion: v1
kind: Service
metadata:
  name: conway-service
  namespace: default
spec:
  selector:
    app: conway
    release: latest
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
      nodePort: null
