apiVersion: apps/v1
kind: Deployment
metadata:
  name: dict-regex-deployment
spec:
  selector:
    matchLabels:
      app: dict-regex
      release: latest
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: dict-regex
        release: latest
    spec:
      containers:
        - name: dict-regex
          image: dict-regex:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
