apiVersion: v1
kind: Service
metadata:
  name:
    dict-regex-service
spec:
  selector:
    app: dict-regex
    release: latest
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http
      nodePort: null
